### ISSUE TITLE
1.15.2 LuckPerms and Prison not loading

### ISSUE THREAD

**Issue by Casper2416** [PrisonTeam/Prison#151]
### Which module are you submitting this issue for?

Paper-spigot #121 1.15.2 Prison v3.2.0 LuckPerms v5.0.72

### Describe the issue you are experiencing.
When i start my server i get the error message:
[17:31:21 ERROR]: Error occurred while enabling Prison v3.2.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
        at tech.mcprison.prison.spigot.permissions.LuckPermissions.<init>(LuckPermissions.java:20) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_221]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_221]
        at tech.mcprison.prison.spigot.SpigotPrison.registerIntegration(SpigotPrison.java:235) ~[?:?]
        at tech.mcprison.prison.spigot.SpigotPrison.initIntegrations(SpigotPrison.java:224) ~[?:?]
        at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:113) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-121]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[patched_1.15.2.jar:git-Paper-121]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 18 more

This can be fixed by unloading LuckPerms, loading Prison and then loading LuckPerms

### Describe the steps to reproduce the problem.
Install LuckPerms-Bukkit-5.0.72 on a Paper #121 1.15.2 server install Prison

**Comment by rbluer** [comment]
Thanks so much for taking the time fill out this report.  I'm glad you have given Prison a try and I greatly appreciate that you are attempting to resolve this issue.  It has been resolved, see below for the solution.

First off though, let me say that LuckPerms really screwed up when the released their v5.0.x plugin.  I can go in to great depths on they did not think through that process and how they could have prevented their plugin from crashing so many server, but I won't (not here anyway).  The side effect of their poor planning are stack traces like what you have reported occurring in many plugins.  I can only hope they have learned their lessons.

Secondly, although we do not officially support Paper directly, I'm wanting to make sure Prison works 100% correctly under Paper, so please feel free to raise any concerns you experiance.  Also LuckPerms v5.0.x is not a supported version for all prior versions of prison.  LuckPerms v5.0.x is fully supported with the upcoming Prison v3.2.1 release (eta unknown right now).

The problem that you are experiencing has been fixed with the latest version of Prison that is under development.  At this time the next major release is not ready to be pushed out, but you can find a development build on our discord server under the channel #support-bleeding. 

Prison Discord: https://discord.gg/DCJ3j6r
#support-bleeding channel

The current plugin is Prison_v3.2.1-alpha.4.jar and may be replaced as newer versions are released.

Since it is a pre-release, there are the possibility of issues, but I will try to make sure everything is functioning correctly.  Also new features may be added and may not be in their final state.  If you have any issues with a pre-release feel free to bring them to my attention within that discord channel and I'll try to get them resolved as quickly as I can.

I'm marking this as bug since LuckPerms v5.0.x did break all prior versions of prison.  I'm also closing this issue since it has already fixed in the pre-release version and that downloadable build artifact is available on the discord server.

Thanks for choosing Prison, and thanks even more so for raising this issue.
   Blue
