### ISSUE TITLE
Null Pointer Exception with PAPI - Prison 3.2

### ISSUE THREAD

**Issue by Stixil** [PrisonTeam/Prison#166]
[17:24:05] [Craft Scheduler Thread - 8/WARN]: [BungeeTabListPlus] Failed to query value for placeholder "%prison_rank%" from PlaceholderAPI
java.lang.NullPointerException: null
	at tech.mcprison.prison.spigot.placeholder.PlaceHolderAPIIntegrationWrapper.onRequest(PlaceHolderAPIIntegrationWrapper.java:73) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.placeholderapi.PlaceholderAPIDataAccess.lambda$new$0(PlaceholderAPIDataAccess.java:38) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-284]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-284]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[17:24:05] [Craft Scheduler Thread - 8/WARN]: [BungeeTabListPlus] Failed to query value for placeholder "%prison_rank_tag%" from PlaceholderAPI
java.lang.NullPointerException: null
	at tech.mcprison.prison.spigot.placeholder.PlaceHolderAPIIntegrationWrapper.onRequest(PlaceHolderAPIIntegrationWrapper.java:73) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:326) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:525) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.placeholderapi.PlaceholderAPIDataAccess.lambda$new$0(PlaceholderAPIDataAccess.java:38) ~[?:?]
	at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
	at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
	at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[?:?]
	at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[?:?]
	at codecrafter47.bungeetablistplus.bukkitbridge.BukkitBridge.lambda$onEnable$3(BukkitBridge.java:128) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-284]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-284]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by GABRYCA** [comment]
Hi.
I'd suggest to try at least an Alpha version, maybe it has already fixed the issue, 
+ /prison version will give a list of placeholders, a bigger one.
To get it, please join the discord server and head on the channel #support-bleeding, you'll find the jar there

**Comment by Stixil** [comment]
Hi, I've not been able to find a link to the Discord, it's not posted on SpigotMC. Thanks!

**Comment by rbluer** [comment]
Stixil thanks for the report...

I updated the code so that won't happen again.  You can download the updated build on our Discord server in the #support-bleeding channel.  

This is a link to the discord channel:
https://discord.gg/R2ffsn

I'm assuming that you do not have ranks module active?  If you don't, I don't understand why you would be using that placeholder.  

If you need more help, please use the discord server for better service.
https://discord.gg/396ed5F

Unfortunately, I am unable to update the github main landing page until we push out the next release.  My hands are tied on that.  Also I do not have access to the spigotmc.org site to update links either. 

Current documents are located here:

https://github.com/PrisonTeam/Prison/blob/bleeding/docs/prison_docs_626_configuring_worldguard_regions.md

I'm closing this ticket since the fix resolves this specific issue and also that you did not indicate you have other problems.

  thanks!
  Blue
