### ISSUE TITLE
After this error timers of all mines, go to a minus position -1 -2 -3 and so on, reset command saves

### ISSUE THREAD

**Issue by iRetri0** [PrisonTeam/Prison#229]
java.util.UnknownFormatConversionException: Conversion = '7'
        at java.util.Formatter.parse(Formatter.java:2750) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2671) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
        at java.lang.String.format(String.java:4140) ~[?:?]
        at tech.mcprison.prison.output.Output.sendMessage(Output.java:471) ~[Prison-3.2.11.jar:?]
        at tech.mcprison.prison.localization.Localizable.sendTo(Localizable.java:361) ~[Prison-3.2.11.jar:?]
        at tech.mcprison.prison.localization.Localizable.sendTo(Localizable.java:378) ~[Prison-3.2.11.jar:?]
        at tech.mcprison.prison.mines.data.MineTasks.broadcastPendingResetMessageToAllPlayersWithRadius(MineTasks.java:318) ~[Prison-3.2.11.jar:?]
        at tech.mcprison.prison.mines.data.MineScheduler.run(MineScheduler.java:365) ~[Prison-3.2.11.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-148]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-148]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-148]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-148]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-148]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-148]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-148]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by rbluer** [comment]
Sounds like you might have edited the language files and inserted a % symbol, or a combination of such, in the wrong place.

If you made changes to the language files, then review what you changed and even compare it against the original messages.  The parameters are critical too and must be expressed as %1, %2, or %3.  You cannot just randomly add % symbols.

The message that appears to be messed up is the **reset_warning** message.  It was as follows and includes something with one of the 7's.
reset_warning=&7All mines are going to reset in &3%1&7.

If you need more help, please visit our discord server.

**Comment by rbluer** [comment]
I'm closing this due to no response.  If you need help, please visit our discord server.

  Thanks...
