### ISSUE TITLE
Broken ranks causes entire plugin to fail to load

### ISSUE THREAD

**Issue by Edgeburn** [PrisonTeam/Prison#253]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### Which module are you submitting this issue for?

Ranks

### Describe the issue you are experiencing.

The plugin throws an exception on server startup. We have never used the ranks feature on our server.

### Describe the steps to reproduce the problem.

It breaks on startup since the update to 1.20.

### Anything else we need to know?

I've attached a ZIP of my Prison plugin folder. Log of prison's startup attempt:

```
[19:02:49 INFO]: [Prison] Enabling Prison v3.3.0-alpha.15
[19:02:49 INFO]: | Prison |  -------------------- <  > ----------------------- (3.3.0-alpha.15)
[19:02:49 INFO]: | Prison |   _____      _                 
[19:02:49 INFO]: | Prison |  |  __ \    (_)                
[19:02:49 INFO]: | Prison |  | |__) | __ _ ___  ___  _ __  
[19:02:49 INFO]: | Prison |  |  ___/ '__| / __|/ _ \| '_ \
[19:02:49 INFO]: | Prison |  | |   | |  | \__ \ (_) | | | |
[19:02:49 INFO]: | Prison |  |_|   |_|  |_|___/\___/|_| |_|
[19:02:49 INFO]: | Prison |  Loading Prison version: 3.3.0-alpha.15
[19:02:49 INFO]: | Prison |  Running on platform: SpigotPlatform
[19:02:49 INFO]: | Prison |  Minecraft version: git-Purpur-2028 (MC: 1.20.1)
[19:02:49 INFO]: | Prison |  Server runtime: just now
[19:02:49 INFO]: | Prison |  Java Version: 17.0.8  Processor cores: 12 
[19:02:49 INFO]: | Prison |  Memory Max: 10.000 GB  Total: 5.742 GB  Free: 2.367 GB  Used: 3.375 GB
[19:02:49 INFO]: | Prison |  Total Server Disk Space: 466.288 GB  Usable: 273.113 GB  Free: 296.869 GB  Used: 169.419 GB
[19:02:49 INFO]: | Prison |  Prison's File Count: 883  Folder Count: 24  Disk Space: 5.898 MB  Other Objects: 0
[19:02:49 INFO]: | Prison |  Prison TPS Average: 0.00  Min: 20.00  Max: 20.00   Interval: 10 ticks  Samples: 0
[19:02:49 INFO]: | Prison |  Enabling and starting...
[19:02:49 INFO]: | Prison |  Root command: /prison   fallback-prefix: prison
[19:02:49 INFO]: | Prison |  Enabled Prison v3.3.0-alpha.15 in 135 milliseconds.
[19:02:49 INFO]: | Prison |  Using version adapter tech.mcprison.prison.spigot.compat.Spigot118
[19:02:49 INFO]: | Prison |  SpigotListener: Trying to register events
[19:02:49 INFO]: | Prison |  EssentialsEconomy is not directly enabled - Available as backup. 
[19:02:49 INFO]: [PlaceholderAPI] Successfully registered expansion: prison [3.3.0-alpha.15]
[19:02:49 WARN]: [PlaceholderAPI] Failed to load expansion PRISON. Identifier is already in use.
[19:02:49 INFO]: | Prison |  Mines Module enablement starting...
[19:02:49 INFO]: | Prison |  Mines Module enabled successfully in 99 milliseconds.
[19:02:49 INFO]: | Prison |  Modules: Prison Ranks, Ladders, and Players are disabled and were not Loaded. 
[19:02:49 INFO]: | Prison |    Prestiges cannot be enabled without ranks being enabled. 
[19:02:49 INFO]: | Prison |    Prison Ranks have been disabled in plugins/Prison/modules.yml.
[19:02:49 INFO]: | Prison |  Modules: Prison sellall module is disabled and was not Loaded. 
[19:02:49 INFO]: | Prison |  Utils Module enablement starting...
[19:02:49 INFO]: | Prison |  Utils Module enabled successfully in 8 milliseconds.
[19:02:49 INFO]: | Prison |  Loaded 12 mines and submitted with a 5000 millisecond offset timing for auto resets.
[19:02:49 WARN]: [PlaceholderAPI] Failed to load expansion prison. Identifier is already in use.
[19:02:49 WARN]: [PlaceholderAPI] Failed to load expansion PRISON. Identifier is already in use.
[19:02:49 INFO]: | Prison |  Total placeholders generated: 704
[19:02:49 INFO]: | Prison |    MINES: 336
[19:02:49 INFO]: | Prison |    MINEPLAYERS: 76
[19:02:49 INFO]: | Prison |    PLAYERBLOCKS: 76
[19:02:49 INFO]: | Prison |    STATSMINES: 216
[19:02:49 INFO]: | Prison |    ALIAS: 352
[19:02:49 INFO]: | Prison |  Total placeholders available to be Registered: 704
[19:02:49 INFO]: | Prison |  AutoManager: AutoFeatures and the Mine module are enabled. Prison will register the selected block break listeners.
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register BlockBreakEvent
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register ExplosiveBlockBreakEvent Listener
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: CrazyEnchants
[19:02:49 INFO]: | Prison |  AutoManager: CrazyEnchants is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: TokenEnchant
[19:02:49 INFO]: | Prison |  AutoManager: TokenEnchant is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: Zenchantments
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register Zenchantments
[19:02:49 INFO]: | Prison |  AutoManagerEventsManager: unregistered a total of 3 event listeners.
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register BlockBreakEvent
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register ExplosiveBlockBreakEvent Listener
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: CrazyEnchants
[19:02:49 INFO]: | Prison |  AutoManager: CrazyEnchants is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: TokenEnchant
[19:02:49 INFO]: | Prison |  AutoManager: TokenEnchant is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: Zenchantments
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register Zenchantments
[19:02:49 ERROR]: Error occurred while enabling Prison v3.3.0-alpha.15 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "tech.mcprison.prison.ranks.PrisonRanks.getPlayerManager()" because the return value of "tech.mcprison.prison.ranks.PrisonRanks.getInstance()" is null
	at tech.mcprison.prison.ranks.data.TopNPlayers.launchTopNPlayerUpdateAsyncTask(TopNPlayers.java:133) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.ranks.data.TopNPlayers.getInstance(TopNPlayers.java:94) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.spigot.SpigotPlatform.prisonVersionFeatures(SpigotPlatform.java:2456) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.spigot.SpigotPrison.onEnableStartup(SpigotPrison.java:385) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:272) ~[Prison-3.3.0-alpha.15.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at java.lang.Thread.run(Thread.java:833) ~[?:?][19:02:49 INFO]: [Prison] Enabling Prison v3.3.0-alpha.15
[19:02:49 INFO]: | Prison |  -------------------- <  > ----------------------- (3.3.0-alpha.15)
[19:02:49 INFO]: | Prison |   _____      _                 
[19:02:49 INFO]: | Prison |  |  __ \    (_)                
[19:02:49 INFO]: | Prison |  | |__) | __ _ ___  ___  _ __  
[19:02:49 INFO]: | Prison |  |  ___/ '__| / __|/ _ \| '_ \
[19:02:49 INFO]: | Prison |  | |   | |  | \__ \ (_) | | | |
[19:02:49 INFO]: | Prison |  |_|   |_|  |_|___/\___/|_| |_|
[19:02:49 INFO]: | Prison |  Loading Prison version: 3.3.0-alpha.15
[19:02:49 INFO]: | Prison |  Running on platform: SpigotPlatform
[19:02:49 INFO]: | Prison |  Minecraft version: git-Purpur-2028 (MC: 1.20.1)
[19:02:49 INFO]: | Prison |  Server runtime: just now
[19:02:49 INFO]: | Prison |  Java Version: 17.0.8  Processor cores: 12 
[19:02:49 INFO]: | Prison |  Memory Max: 10.000 GB  Total: 5.742 GB  Free: 2.367 GB  Used: 3.375 GB
[19:02:49 INFO]: | Prison |  Total Server Disk Space: 466.288 GB  Usable: 273.113 GB  Free: 296.869 GB  Used: 169.419 GB
[19:02:49 INFO]: | Prison |  Prison's File Count: 883  Folder Count: 24  Disk Space: 5.898 MB  Other Objects: 0
[19:02:49 INFO]: | Prison |  Prison TPS Average: 0.00  Min: 20.00  Max: 20.00   Interval: 10 ticks  Samples: 0
[19:02:49 INFO]: | Prison |  Enabling and starting...
[19:02:49 INFO]: | Prison |  Root command: /prison   fallback-prefix: prison
[19:02:49 INFO]: | Prison |  Enabled Prison v3.3.0-alpha.15 in 135 milliseconds.
[19:02:49 INFO]: | Prison |  Using version adapter tech.mcprison.prison.spigot.compat.Spigot118
[19:02:49 INFO]: | Prison |  SpigotListener: Trying to register events
[19:02:49 INFO]: | Prison |  EssentialsEconomy is not directly enabled - Available as backup. 
[19:02:49 INFO]: [PlaceholderAPI] Successfully registered expansion: prison [3.3.0-alpha.15]
[19:02:49 WARN]: [PlaceholderAPI] Failed to load expansion PRISON. Identifier is already in use.
[19:02:49 INFO]: | Prison |  Mines Module enablement starting...
[19:02:49 INFO]: | Prison |  Mines Module enabled successfully in 99 milliseconds.
[19:02:49 INFO]: | Prison |  Modules: Prison Ranks, Ladders, and Players are disabled and were not Loaded. 
[19:02:49 INFO]: | Prison |    Prestiges cannot be enabled without ranks being enabled. 
[19:02:49 INFO]: | Prison |    Prison Ranks have been disabled in plugins/Prison/modules.yml.
[19:02:49 INFO]: | Prison |  Modules: Prison sellall module is disabled and was not Loaded. 
[19:02:49 INFO]: | Prison |  Utils Module enablement starting...
[19:02:49 INFO]: | Prison |  Utils Module enabled successfully in 8 milliseconds.
[19:02:49 INFO]: | Prison |  Loaded 12 mines and submitted with a 5000 millisecond offset timing for auto resets.
[19:02:49 WARN]: [PlaceholderAPI] Failed to load expansion prison. Identifier is already in use.
[19:02:49 WARN]: [PlaceholderAPI] Failed to load expansion PRISON. Identifier is already in use.
[19:02:49 INFO]: | Prison |  Total placeholders generated: 704
[19:02:49 INFO]: | Prison |    MINES: 336
[19:02:49 INFO]: | Prison |    MINEPLAYERS: 76
[19:02:49 INFO]: | Prison |    PLAYERBLOCKS: 76
[19:02:49 INFO]: | Prison |    STATSMINES: 216
[19:02:49 INFO]: | Prison |    ALIAS: 352
[19:02:49 INFO]: | Prison |  Total placeholders available to be Registered: 704
[19:02:49 INFO]: | Prison |  AutoManager: AutoFeatures and the Mine module are enabled. Prison will register the selected block break listeners.
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register BlockBreakEvent
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register ExplosiveBlockBreakEvent Listener
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: CrazyEnchants
[19:02:49 INFO]: | Prison |  AutoManager: CrazyEnchants is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: TokenEnchant
[19:02:49 INFO]: | Prison |  AutoManager: TokenEnchant is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: Zenchantments
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register Zenchantments
[19:02:49 INFO]: | Prison |  AutoManagerEventsManager: unregistered a total of 3 event listeners.
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register BlockBreakEvent
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register ExplosiveBlockBreakEvent Listener
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: CrazyEnchants
[19:02:49 INFO]: | Prison |  AutoManager: CrazyEnchants is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: TokenEnchant
[19:02:49 INFO]: | Prison |  AutoManager: TokenEnchant is not loaded
[19:02:49 INFO]: | Prison |  AutoManager: checking if loaded: Zenchantments
[19:02:49 INFO]: | Prison |  AutoManager: Trying to register Zenchantments
[19:02:49 ERROR]: Error occurred while enabling Prison v3.3.0-alpha.15 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "tech.mcprison.prison.ranks.PrisonRanks.getPlayerManager()" because the return value of "tech.mcprison.prison.ranks.PrisonRanks.getInstance()" is null
	at tech.mcprison.prison.ranks.data.TopNPlayers.launchTopNPlayerUpdateAsyncTask(TopNPlayers.java:133) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.ranks.data.TopNPlayers.getInstance(TopNPlayers.java:94) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.spigot.SpigotPlatform.prisonVersionFeatures(SpigotPlatform.java:2456) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.spigot.SpigotPrison.onEnableStartup(SpigotPrison.java:385) ~[Prison-3.3.0-alpha.15.jar:?]
	at tech.mcprison.prison.spigot.SpigotPrison.onEnable(SpigotPrison.java:272) ~[Prison-3.3.0-alpha.15.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:440) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2028]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

[Prison.zip](https://github.com/PrisonTeam/Prison/files/12435191/Prison.zip)

**Comment by rbluer** [comment]
Sorry, I'm just seeing this issue right now.

As I've tried to make it perfectly clear, please use support on our discord server.  You would have seen this issue was fixed and an update was posted on our discord server on September 24th.

I hope you figured that out.  Sorry for any confusion this may have caused.
