### ISSUE TITLE
[Prison Bug] mines unable to refresh

### ISSUE THREAD

**Issue by damahouH** [PrisonTeam/Prison#259]
**Support is available on Prison's Discord server**
Please visit our discord server for help and bug reporting: [Prison Discord Server](https://discord.gg/DCJ3j6r).  You can report bugs here, but our discord server can provide quicker turn around time.

**Describe the bug**
mines unable to refresh

 [Prison] Task #72 for Prison v3.3.0-alpha.16 generated an exception
java.util.UnknownFormatConversionException: Conversion = 'm'
        at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2855) ~[?:?]
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2891) ~[?:?]
        at java.util.Formatter.parse(Formatter.java:2747) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2671) ~[?:?]
        at java.util.Formatter.format(Formatter.java:2625) ~[?:?]
        at java.lang.String.format(String.java:4147) ~[?:?]
        at tech.mcprison.prison.output.Output.sendMessage(Output.java:625) ~[?:?]
        at tech.mcprison.prison.localization.Localizable.sendTo(Localizable.java:373) ~[?:?]
        at tech.mcprison.prison.localization.Localizable.sendTo(Localizable.java:394) ~[?:?]
        at tech.mcprison.prison.mines.data.MineTasks.broadcastPendingResetMessageToAllPlayersWithRadius(MineTasks.java:330) ~[?:?]
        at tech.mcprison.prison.mines.data.MineScheduler.run(MineScheduler.java:374) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by rbluer** [comment]
Thanks for reporting that issue.

There is a fix for that on our discord server.

I should push out an update with that fix.

Sorry for any issues that may have caused.
